### ISSUE TITLE
Check if layout works for multiple resolutions

### ISSUE THREAD

**Issue by ariostas** [hsf-training/training-center#37]
When looking at the website on a lower resolution screen there can be issues with overlapping text.

This might not be a big deal since even phones have pretty high resolution these days, but it might be worth considering.

![Screenshot 2023-12-19 at 3 20 26 PM](https://github.com/hsf-training/training-center/assets/7596837/16d5b7a8-0c9c-4dba-a616-8eab387fa7b7)

**Comment by klieret** [comment]
This should be resolved with #2, it's an issue with how these are implemented. I'm going to close this because it's too broad of a category.
