### ISSUE TITLE
Make it more obvious if training material is not stable

### ISSUE THREAD

**Issue by klieret** [hsf-training/training-center#7]
Option 1: Colored "Ribbon" on the bottom spelling "Status: beta" etc.

<img width="713" alt="image" src="https://github.com/hsf-training/training-center-aniket/assets/13602468/c3aa906a-5279-4251-be75-dd53de0d59c6">

**Comment by ariostas** [comment]
How do you feel about something like this? Maybe a whole colored ribbon is a bit too much visual clutter.

![Screenshot 2023-12-19 at 10 44 11 AM](https://github.com/hsf-training/training-center/assets/7596837/6c550bbf-0673-4731-8439-218a1e3c4ed0)

**Comment by klieret** [comment]
Looks great! Maye slightly expanding it by writing "Early development" and "Beta testing" ?

**Comment by klieret** [comment]
Looks like you already had this implemented? I don't think @richa2710  had been working on this yet

**Comment by ariostas** [comment]
For the stable ones should we leave the green dot or just remove it?

**Comment by klieret** [comment]
I'd remove it! Less clutter is always better :)
